FROM python:3.5 # 기본 이미지를 python3.5 로 설정
ENV PYTHONUNBUFFERED 1 # 환경변수 설정 삭제할까?
RUN mkdir /django # docker 내에서 /code 라는 이름의 폴더 생성
WORKDIR /django # docker 내에서 코드를 실행할 폴더 위치를 /code 로 지정
ADD requirements.txt /code/ # 로컬의 requirements.txt 파일을 docker /code/ 폴더로 마운트
RUN pip install -r requirements.txt # docker 내 requirements.txt 파일을 이용하여 패키지 설치
ADD . /django/ # 로컬 내 현재 위치에 있는 모든 파일 및 폴더를 docker 의 /code/ 폴더로 마운트d