# FROM python:latest # 기본 이미지를 python3.5 로 설정
# RUN mkdir /portfolio # docker 내에서 /code 라는 이름의 폴더 생성
# WORKDIR /portfolio # docker 내에서 코드를 실행할 폴더 위치를 /code 로 지정
# ADD requirements.txt /code/ # 로컬의 requirements.txt 파일을 docker /code/ 폴더로 마운트
# RUN pip install -r requirements.txt # docker 내 requirements.txt 파일을 이용하여 패키지 설치
# ADD . /portfolio/ # 로컬 내 현재 위치에 있는 모든 파일 및 폴더를 docker 의 /code/ 폴더로 마운트d

FROM ubuntu

# 파이썬 설치
RUN apt-get update
RUN apt-get install --assume-yes python3
RUN apt-get install --assume-yes python3-pip

# 작업할 폴더명을 지정한다.
WORKDIR /home/ubuntu/portfolio

# 로컬에 있는 파일을 도커 컨테이너 안 리눅스 경로로 이동시킨다.
ADD . /home/ubuntu/portfolio

# 장고 설치
RUN pip3 install -r /home/ubuntu/portfolio/requirements.txt

# 장고 실행
CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
